config/routes.rb
Rails.application.routes.draw do
  get 'requests/create'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :users do
    resources :requests do
    end
  end

  match '/users/:user_id/requests/:id/claim', to: 'requests#claim', as: 'claim_request', via: :post
  match '/users/:user_id/requests/:id/unclaim', to: 'requests#unclaim', as: 'unclaim_request', via: :post
  match '/unsubscribe', to: 'requests#unsubscribe', as: 'unsubscribe', via: :get

  root 'users#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates :password, presence: true, length: {minimum: 5, maximum: 120}, on: :create
  validates :password, length: {minimum: 5, maximum: 120}, on: :update, allow_blank: true
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :usergrades
  has_many :grades, through: :usergrades
  has_many :userschools
  has_many :schools, through: :userschools
  has_many :usersubjects
  has_many :subjects, through: :usersubjects
  has_many :userrequests, dependent: :destroy
  has_many :requests, through: :userrequests



  def name
    "#{first_name} #{last_name}"
  end

  def role_label
    if self.super_admin?
      'Super Admin'
    elsif self.teacher?
      'Teacher'
    elsif self.substitute
      'Substitute'
    elsif self.admin?
      'Admin'
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource

  # GET /users
  # GET /users.json
  def index
    if current_user.super_admin?
      @users = User.all

    elsif current_user.teacher?
      @user = current_user
      @requests = @user.requests
      @future_requests = @user.requests.where("date >= ?", Date.today)


    elsif current_user.substitute?
      @user = current_user
      @sub_schools = @user.schools.map do |school|
        "%#{school.name}%"
      end
      @requests = User.where(teacher: true).joins(:requests, :schools).where("schools.name ILIKE ANY ( array[?] )", @sub_schools).uniq

      @open_request_check = []

      @requests.map do |user|
         user.requests.where(active: true, sub_claim: false).map do |request|
           @open_request_check << request
         end
       end

      @claims = current_user.requests.order(date: :ASC)

      @future_requests = @user.requests.where("date >= ?", Date.today)



    elsif current_user.admin?
      @users = User.joins(:school).where(:schools => {:name => current_user.schools})
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @request = @user.requests.new
  end

  # GET /users/new
  def new
    @user = User.new

  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to root_path, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :teacher, :substitute, :admin, :super_admin, :password, :grade_ids => [], :subject_ids => [], :school_ids => [], :request_ids => [])
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_admin.html.erb
<h2>Imma an ADMIN!!</h2>

app/views/users/_form.html.erb
<%= simple_form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :email %>
  <!-- <%= f.input :password %> -->
<% if current_user.super_admin? %>
  <%= f.input :teacher %>
  <%= f.input :substitute %>
  <%= f.input :admin %>
  <%= f.input :super_admin %>
<% end %>

  <%= f.association :grades,   as: :check_boxes  %>
  <%= f.association :subjects,   as: :check_boxes  %>
  <%= f.association :schools,   as: :check_boxes  %>


<% if current_user.teacher? %>

<% end %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                users_path, :class => 'btn btn-default' %>
<% end %>

app/views/users/_sub.html.erb
<% unless @open_request_check.any? %>
  <h2>Hello, <%= @user.name %>! You currently have no pending or assigned jobs.  Please check back at a later date.</h2>
<% end %>


<% if @open_request_check.any? %>
<h2 class="text-center"><%= current_user.name %></h2>
<h3>Open Requests</h3>
  <div class="table-responsive">
    <table class="table table-bordered table-hover table-sm">
      <tr>
        <th>Date Requested</th>
        <th>Teacher Requesting</th>
        <th>School</th>
        <th>Grade</th>
        <th>Subject(s)</th>
        <th>Notes</th>
        <th>Action</th>
      </tr>
        <% @requests.each do |user| %>
          <% user.requests.where(active: true, sub_claim: false).each do |request| %>
      <tr>
        <td><%= request.date.strftime('%D') %></td>
        <% request.users.each do |user| %>
        <td><%= user.name %></td>
        <% user.schools.each do |school| %>
        <td><%= school.name %></td>
        <% end %>
        <td><% user.grades.each do |grade| %>
          <%= grade.name %> <br>
        <% end %></td>
        <td><% user.subjects.each do |subject| %>
            <%= subject.name %> <br>
        <% end %></td>
        <% end %>
        <td><%= request.notes %></td>
        <td><%= link_to "Claim Job",  claim_request_path(current_user, request), class: "btn btn-primary btn-xs", method: :post %></td>
      </tr>
      <% end %>
    <% end %>
      </table>
  </div>

  <% end %>



<% if @future_requests.where(active: true, sub_claim: true).any? %>
  <h3>Your Upcoming Assignments</h3>
    <div class="table-responsive">
      <table class="table table-bordered table-hover table-sm">
        <tr>
          <th>Date Requested</th>
          <th>Teacher Requesting</th>
          <th>School</th>
          <th>Grade(s)</th>
          <th>Subject(s)</th>
          <th>Notes</th>
          <th>Action</th>
        </tr>
    <% @future_requests.where(active: true, sub_claim: true).each do |request| %>
        <tr>
          <td><%= request.date.strftime('%D') %></td>
          <% request.users.where(teacher: true).each do |user| %>
            <td><%= user.name %></td>
            <% user.schools.each do |school| %>
              <td><%= school.name %></td>
            <% end %>
            <td><% user.grades.each do |grade| %>
              <%= grade.name %> <br>
            <% end %></td>
            <td><% user.subjects.each do |subject| %>
              <%= subject.name %> <br>
            <% end %></td>
          <% end %>
          <td><%= request.notes %></td>
          <td><%= button_to "Cancel", unclaim_request_path(current_user, request), method: :post, data: {confirm: "You sure?"}, class: "btn btn-warning btn-xs" %></td>
        </tr>
    <% end %>
    </table>
    </div>
<% end %>


<% if @claims.where(active: false, sub_claim: true).any? %>
<h3>Previous Jobs</h3>
    <div class="table-responsive">
      <table class="table table-bordered table-hover table-sm">
        <tr>
          <th>Date Requested</th>
          <th>Teacher Requesting</th>
          <th>School</th>
          <th>Grade(s)</th>
          <th>Subject(s)</th>
          <th>Notes</th>
        </tr>
      <% @claims.where(active: false, sub_claim: true).each do |request| %>
        <tr>
          <td><%= request.date.strftime('%D') %></td>
          <% request.users.where(teacher: true).each do |user| %>
            <td><%= user.name %></td>
            <% user.schools.each do |school| %>
              <td><%= school.name %></td>
            <% end %>
            <td><% user.grades.each do |grade| %>
              <%= grade.name %> <br>
            <% end %></td>
            <td><% user.subjects.each do |subject| %>
              <%= subject.name %> <br>
            <% end %></td>
          <% end %>
          <td><%= request.notes %></td>
        </tr>
      <% end %>
      </table>
    </div>
<% end %>

app/views/users/_super_admin.html.erb
<% School.all.each do |school| %>
  <h3><%= school.name %></h3>
    <div class="table-responsive">
      <table class="table table-striped table-sm table-hover">
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Role</th>
        </tr>
    <% school.users.each do |user| %>
        <tr>
          <td><%= link_to user.name, user_path(user) %></td>
          <td><%= mail_to user.email %></td>
          <td><%= user.role_label %></td>
        </tr>
    <% end %>
      </table>
    </div>
<% end %>

app/views/users/_teacher.html.erb
<h2 class='text-center'><%= current_user.name %></h2>

<h3 class="text-center">Create a new request</h3>


    <div class="row center">
        <div class='col-sm-6'>
          <%= simple_form_for [@user, @user.requests.build], :html => { :class => 'form-horizontal' } do |f| %>
            <%= f.input :date, as: :date, order: [:month, :day, :year] %>
            <%= f.input :notes, as: :text %>

            <%= f.button :submit, :class => 'btn-success', data: {confirm: "You sure? You are about to message available substitutes."} %>
          <% end %>
        </div>
    </div>


<% if @requests.where(active: true).any? %>
  <h3>Requests Waiting to be Filled</h3>
    <div class="table-responsive">
      <table class="table table-bordered table-hover table-sm">
        <tr>
          <th>Date Requested</th>
          <th>Notes</th>
          <th>Action</th>
        </tr>
    <% @requests.where(active: true, sub_claim: false).each do |request| %>
        <tr>
          <td><%= request.date.strftime('%D') %></td>
          <td><%= request.notes %></td>
          <td><%= link_to "Cancel", user_request_path(current_user, request), method: :delete, data: {confirm: "You sure?"}, class: "btn btn-warning btn-xs" %></td>
        </tr>
    <% end %>
    </table>
    </div>
<% end %>

<% if @future_requests.where(active: true, sub_claim: true).any? %>
<h3>Upcoming Filled Requests</h3>
  <div class="table-responsive">
    <table class="table table-bordered table-hover table-sm">
      <tr>
        <th>Date</th>
        <th>Substitute</th>
        <th>Notes</th>
        <th>Status</th>
        <th>Action</th>
      </tr>
    <% @future_requests.where(active: true, sub_claim: true).each do |request| %>
      <tr>
        <td><%= request.date.strftime('%D') %></td>
        <% request.users.where(substitute: true).each do |user| %>
        <td><%= mail_to user.email, user.name %></td>
        <% end %>
        <td><%= request.notes %></td>
        <td><%= "Filled" %></td>
        <td><%= link_to "Cancel", user_request_path(current_user, request), method: :delete, data: {confirm: "You sure?"}, class: "btn btn-warning btn-xs" %></td>
      </tr>
    <% end %>
    </table>
  </div>
<% end %>



<% if @requests.where(active: false).any? %>
<h3>Closed Requests</h3>
  <div class="table-responsive">
    <table class="table table-bordered table-hover table-sm">
      <tr>
        <th>Date Requested</th>
        <th>Notes</th>
        <th>Claimed by</th>
      </tr>
      <% @requests.where(active: false).each do |request| %>
      <tr>
        <td><%= request.date.strftime('%D') %></td>
        <td><%= request.notes %></td>
        <td><% request.users.where(substitute: true).each do |user| %>
          <%= user.name %>
          <% end %></td>
      </tr>
      <% end %>
    </table>
  </div>
<% end %>

<script type="text/javascript">
    $(function () {
        $('#datetimepicker4').datetimepicker();
    });
</script>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<% if current_user.super_admin? %>
  <%= render "super_admin", object: @users %>
<% end %>

<% if current_user.teacher? %>
  <%= render "teacher" %>
<% end %>

<% if current_user.substitute? %>
  <%= render "sub" %>
<% end %>

<% if current_user.admin? %>
  <%= render "admin", object: @users %>
<% end %>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/show.html.erb
<h2><%= @user.name %> - <%= "Grade".pluralize(@user.grades.count) %> - <% @user.grades.each do |grade|%> <%= grade.name %>   <% end %></h2>

<h3>Create a new request</h3>

<%= simple_form_for [@user, @user.requests.build], :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :date, as: :date, order: [:month, :day, :year]  %>
  <%= f.input :notes %>

  <%= f.button :submit, :class => 'btn-primary' %>

  <br>

  <h3>Active Requests</h3>
    <table class="table table-striped table-bordered">
      <tr>
        <th>Date</th>
        <th>Notes</th>
      </tr>
    <% @user.requests.where(active: true).each do |request| %>
      <tr>
        <td><%= request.date.strftime('%D') %></td>
        <td><%= request.notes %></td>
      </tr>
    <% end %>
    </table>
  <h3>Closed Requests</h3>
  <table class="table table-striped">
    <tr>
      <th>Date</th>
      <th>Notes</th>
    </tr>
  <% @user.requests.where(active: false).each do |request| %>
    <tr>
      <td><%= request.date.strftime('%D') %></td>
      <td><%= request.notes %></td>
    </tr>
  <% end %>
  </table>


<% end %>